version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
  postgres_exporter:
    container_name: postgres_exporter
    image: quay.io/prometheuscommunity/postgres-exporter:v0.10.1
    ports:
      - 9187:9187
    environment:
      - "DATA_SOURCE_NAME=postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable"
    restart: always
    depends_on:
      - postgres
volumes:
  postgres_volume: