spring:
  session:
    store-type: JDBC
  profiles:
    active: postgresql
logging:
  level:
    web: DEBUG
#    sql: DEBUG
server:
  error:
    include-binding-errors: ALWAYS
    include-message: ALWAYS
    include-exception: true
    include-stacktrace: ALWAYS
    path: /error
    whitelabel:
      enabled: true
